spring.application.name=alumni-portal
spring.datasource.url=postgresql://alumni_db_iama_user:A8T7IhAufBFtvxffvQNADPVixGqzIE3y@dpg-d6poevlm5p6s73fo366g-a/alumni_db_iama
spring.datasource.username=alumni_db_iama_user
spring.datasource.password=A8T7IhAufBFtvxffvQNADPVixGqzIE3y

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
server.port=8080

server.servlet.session.timeout=5m
